import Header from '@/components/Header';
import LotteryEntrance from '@/components/LotteryEntrance';
import Head from 'next/head';
import { useMoralis } from 'react-moralis';

const supportedChains = ['31337', '5'];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        {isWeb3Enabled ? (
          <div>
            {supportedChains.includes(
              parseInt(chainId as string).toString()
            ) ? (
              <div className="flex flex-row">
                <LotteryEntrance />
              </div>
            ) : (
              <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
            )}
          </div>
        ) : (
          <div>Please connect to a Wallet</div>
        )}
      </div>
    </>
  );
}
